package com.algotic.model.response.paytm;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;
import lombok.Builder;

@Builder
public record OrderBookData(
        @JsonProperty("txn_type") String transactionType,
        @JsonProperty("exchange") String exchange,
        @JsonProperty("segment") String segment,
        @JsonProperty("product") String productCode,
        @JsonProperty("security_id") String scripCode,
        @JsonProperty("quantity") Integer quantity,
        @JsonProperty("validity") String retension,
        @JsonProperty("order_type") String orderType,
        @JsonProperty("price") BigDecimal price,
        @JsonProperty("trigger_price") BigDecimal triggerPrice,
        @JsonProperty("off_mkt_flag") String amoOrder,
        @JsonProperty("source") String source,
        @JsonProperty("mkt_type") String marketType,
        @JsonProperty("order_no") String orderNumber,
        @JsonProperty("serial_no") String serialNumber,
        @JsonProperty("group_id") String groupId,
        @JsonProperty("leg_no") String legNumber,
        @JsonProperty("algo_ord_no") String algoOrderNumber,
        @JsonProperty("status") String status,
        @JsonProperty("exch_order_no") String exchangeOrderNumber,
        @JsonProperty("exch_order_time") String exchangeOrderTime,
        @JsonProperty("traded_qty") Integer tradeQty,
        @JsonProperty("remaining_quantity") Integer remaningQty,
        @JsonProperty("avg_traded_price") BigDecimal avgTradePrice,
        @JsonProperty("display_name") String displayName,
        @JsonProperty("order_date_time") String orderDateTime,
        @JsonProperty("last_updated_time") String lastModifiedTime,
        @JsonProperty("reason_description") String reasonDescription,
        @JsonProperty("pr_abstick_value") String prAbsStickValue,
        @JsonProperty("sl_abstick_value") String slAbstickValue,
        @JsonProperty("isin") String isin,
        @JsonProperty("child_leg_unq_id") String childLEgUniqueId,
        @JsonProperty("ref_ltp") String refLtp,
        @JsonProperty("display_status") String displayStatus,
        @JsonProperty("display_product") String displayProduct,
        @JsonProperty("display_order_type") String displayOrderType,
        @JsonProperty("display_validity") String displayValidity,
        @JsonProperty("tick_size") String tickSize,
        @JsonProperty("error_code") String errorCode,
        @JsonProperty("strategy_id") String strategyId,
        @JsonProperty("placed_by") String placedBy,
        @JsonProperty("lot_size") String lotSize,
        @JsonProperty("strike_price") String strikePrice,
        @JsonProperty("expiry_date") String expiryDate,
        @JsonProperty("opt_type") String optType,
        @JsonProperty("instrument") String instrument,
        @JsonProperty("channel") String channel,
        @JsonProperty("instrument_type") String instrumentType,
        @JsonProperty("tag_type") String tagType,
        @JsonProperty("algo_module") String algoModule,
        @JsonProperty("tag_id") String tagId) {}
